name: Checksum Check
inputs:
  checksum-name:
    type: string
    required: true
    description: The name of the GitHub artifact containing the checksum that will be compared against
  checksum-location:
    type: string
    required: true
    description: Location of the GitHub artifact containing the checksum that will be compared against
outputs:
  result:
    value: ${{ steps.check.outputs.result }}
    description: The result of the comparison between the artifact and the latest ground truth
  ground-truth-version:
    value: ${{ steps.ground-truth.outputs.version }}
    description: The ground truth version compared against the given artifact
runs:
  using: composite
  steps:
    - name: Determine Tag to Check Against
      shell: bash
      id: ground-truth
      run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

    - name: Compare Checksum against ${{ steps.ground-truth.outputs.version }}
      # we use the full `bash {0}` syntax instead of `bash` because we don't want the
      # assumed `-e` (exit on error): the nonzero exit code on `diff` is actually used later on.
      shell: bash {0}
      id: check
      run: |
        git checkout ${{ steps.ground-truth.outputs.version }}
        diff ${{ inputs.checksum-location }}/CHECKSUM CHECKSUM
        if [ "$?" -eq 0 ]; then
          echo "::notice::The generated checksum in the '${{ inputs.checksum-name }}' artifact is the same as the checksum tagged as '${{ steps.ground-truth.outputs.version }}'"
          echo "result=true" >> $GITHUB_OUTPUT
        else
          echo "::error::The generated checksum in the '${{ inputs.checksum-name }}' artifact is different to the checksum tagged as '${{ steps.ground-truth.outputs.version }}'"
          echo "result=false" >> $GITHUB_OUTPUT
        fi